spring:
  application:
    name: user-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
  grpc:
    client:
      channels:
        local:
          address: 0.0.0.0:9999

