eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
spring:
  cloud:
    config:
      override-system-properties: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:9090/realms/novaops}
  virtual:
    threads:
      enabled: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    enabled: false
    path: /docs
    operationsSorter: method
    display-request-duration: true
    oauth:
      client-id: ${keycloak.client-id}
      client-secret: ${keycloak.client-secret}
      scopes: openid profile
  #    oauth2-redirect-url: ${application.backend-url}/swagger-ui/oauth2-redirect.html
  default-produces-media-type: application/json

keycloak:
  realm: novaops
  client-id: ${KEYCLOAK_CLIENT_ID:novaops-backend}
  client-secret: ${KEYCLOAK_CLIENT_SECRET} # The secret for the client, will be loaded from the vault
  url: ${KEYCLOAK_URL:http://localhost:9090}
  default-user-password: ${DEFAULT_USER_PASSWORD} # The initial password for the default user (will be changed on first login)


management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "health,info"
  health:
    circuitbreakers:
      enabled: true

logging:
  level:
    org.springframework.security: DEBUG
