spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/novaops}?currentSchema=user-service
    username: ${DB_USERNAME} # will be loaded from the vault
    password: ${DB_PASSWORD} # will be loaded from the vault
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: user-service
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    schemas: user-service
    table: flyway_history

  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
      group-id: ${KAFKA_GROUP_ID:user-service-group}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: "org.keycloak.events.Event:com.novaops.userservice.infrastructure.adapter.messaging.KeycloakEvent"
server:
  port: 8081